import os
import mysql.connector as mc
from dotenv import load_dotenv

load_dotenv()

con = mc.connect(
    host=os.getenv("DB_HOST", "localhost"),
    user=os.getenv("DB_USER", "root"),
    password=os.getenv("DB_PASSWORD")
)

print("successful")
cur=con.cursor()
cur2=con.cursor(dictionary=True)
cur.execute("CREATE DATABASE IF NOT EXISTS LIBRARYDB")
cur.execute("USE LIBRARYDB")
cur.execute("CREATE TABLE IF NOT EXISTS ADMINP(ADMIN_ID INT AUTO_INCREMENT PRIMARY KEY,USERNAME VARCHAR(40) UNIQUE,PASSWORD VARCHAR(17) UNIQUE,FULL_NAME VARCHAR(40),GENDER VARCHAR(8),MOBILE_NUMBER VARCHAR(11),QUALIFICATION VARCHAR(30),ADDRESS VARCHAR(100))")
cur.execute("CREATE TABLE IF NOT EXISTS LIBRARIAN(LIBRARIAN_ID INT AUTO_INCREMENT PRIMARY KEY,USERNAME VARCHAR(40) UNIQUE,PASSWORD VARCHAR(17) UNIQUE,NAME VARCHAR(40),EMAIL VARCHAR(40),GENDER VARCHAR(8),MOBILE_NO VARCHAR(11),QUALIFICATION VARCHAR(40))")
cur.execute("CREATE TABLE IF NOT EXISTS STUDENT( STUDENT_ID INT AUTO_INCREMENT PRIMARY KEY,USERNAME VARCHAR(40) UNIQUE,PASSWORD VARCHAR(17) UNIQUE,NAME VARCHAR(40),COURSE VARCHAR(30),SEMESTER INT(1),EMAIL VARCHAR(40),MOBILE_NO VARCHAR(12),BOOKS_ISSUED INT(2))")
cur.execute("CREATE TABLE IF NOT EXISTS BOOKS(BOOK_ID INT PRIMARY KEY,TITLE VARCHAR(50),AUTHOR VARCHAR(50),ISBN VARCHAR(30),CATEGORY VARCHAR(50),YEAR INT(4),STATUS VARCHAR(50),PUBLISHER VARCHAR(50),AVAILABLE  INT(3),OUT_OF INT(3),PUBLISHER VARCHAR(50),BDESCRIPTION VARCHAR(255))")
cur.execute("CREATE TABLE IF NOT EXISTS ADMIN_NOTICE(NOTICE_ID INT AUTO_INCREMENT PRIMARY KEY,NDATE DATE ,NTIME TIME ,NFROM VARCHAR(30),NTO VARCHAR(30), SUBJECT VARCHAR(30),CONTENT VARCHAR(100),RECEIVER VARCHAR(30),NSENDER VARCHAR(30),READ_STATUS INT DEFAULT 0)")

cur.execute("""
    CREATE TABLE IF NOT EXISTS BOOK_ISSUES (
        ISSUE_ID INT AUTO_INCREMENT PRIMARY KEY,
        BOOK_ID INT,
        STUDENT_ID INT,
        ISSUE_DATE DATE,
        RETURN_DATE DATE,
        ACTUAL_RETURN_DATE DATE,
        STATUS VARCHAR(20),
        FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID) ON DELETE CASCADE,
        FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID) ON DELETE CASCADE
    )
""")

cur.execute("""
    CREATE TABLE IF NOT EXISTS NOTIFICATIONS (
        NOTIFICATION_ID INT AUTO_INCREMENT PRIMARY KEY,
        STUDENT_ID VARCHAR(15),
        TITLE VARCHAR(100),
        MESSAGE VARCHAR(255),
        DATE DATE,
        TIME TIME,
        READ_STATUS BOOLEAN DEFAULT FALSE,
        FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID) ON DELETE CASCADE
    )
""")

cur.execute("""
    CREATE TABLE IF NOT EXISTS BOOK_REQUESTS (
        REQUEST_ID INT AUTO_INCREMENT PRIMARY KEY,
        STUDENT_ID INT,
        STUDENT_NAME VARCHAR(50),
        BOOK_ID INT,
        TITLE VARCHAR(50),
        PUBLISHER VARCHAR(50),
        REQUEST_DATE DATE,
        STATUS VARCHAR(20),
        ISSUE_DATE DATE,
        DUE_DATE DATE,
        FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID) ON DELETE CASCADE,
        FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID) ON DELETE CASCADE
    )
""")
cur.execute("CREATE TABLE IF NOT EXISTS BOOKHISTORY(ISSUE_ID INT PRIMARY KEY,BOOK_ID INT,BOOK VARCHAR(50),STUDENT_ID INT,STUDENT VARCHAR(50),ISSUE_DATE DATE,DUE_DATE DATE,RETURN_DATE DATE,DAYS_OVERDUE INT,FINE VARCHAR(10),STATUS VARCHAR(30))")
cur.execute("CREATE TABLE IF NOT EXISTS FINE(FINE_ID INT AUTO_INCREMENT PRIMARY KEY,STUDENT_ID VARCHAR(15),SNAME VARCHAR(50),BOOK_ID INT,ISSUE_ID INT,DUE_DATE DATE,RETURN_DATE DATE,REASON VARCHAR(50) ,FINE_AMOUNT FLOAT,PAID BOOLEAN DEFAULT FALSE,FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID) ON DELETE CASCADE,FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID) ON DELETE CASCADE)")
cur.execute("""CREATE TABLE IF NOT EXISTS notices (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255),
  content TEXT,
  date DATE,
  sender VARCHAR(100),
  recipient VARCHAR(100),
  student_id VARCHAR(20),
  student_name VARCHAR(100),
  course VARCHAR(100)
)""")

cur.execute("CREATE TABLE IF NOT EXISTS LDEFAULT(FINE INT DEFAULT 10,DNOTICE VARCHAR(50))")
cur.execute("""
CREATE TABLE if not exists subscription_plans (
    plan_id VARCHAR(20) PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    duration_days INT NOT NULL,
    benefits TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
""")
cur.execute("""CREATE TABLE if not exists  subscriptions (
    subscription_id VARCHAR(10) PRIMARY KEY,
    student_id VARCHAR(10) NOT NULL,
    plan_id VARCHAR(20) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    status ENUM('active', 'expired', 'pending') NOT NULL DEFAULT 'active',
    payment_method ENUM('cash', 'transaction', 'card') NOT NULL,
    transaction_id VARCHAR(50) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP  
);
""")


def add_missing_columns():
    def column_exists(cursor, table_name, column_name):
        cursor.execute(f"""
            SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
            WHERE TABLE_NAME = %s AND COLUMN_NAME = %s AND TABLE_SCHEMA = DATABASE()
        """, (table_name, column_name))
        return cursor.fetchone()[0] == 1

    columns = {
        "student_id": "VARCHAR(20)",
        "student_name": "VARCHAR(100)",
        "course": "VARCHAR(100)"
    }

    for column, datatype in columns.items():
        if not column_exists(cur, "notices", column):
            cur.execute(f"ALTER TABLE notices ADD COLUMN {column} {datatype}")
            print(f"✅ Column '{column}' added to 'notices'")
        else:
            print(f"ℹ️ Column '{column}' already exists")

# Call the function to safely add columns
add_missing_columns()
cur.execute("""CREATE TABLE IF NOT EXISTS MARK_ATTENDANCE (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  STUDENT_ID VARCHAR(15) ,
  DATE DATE,
  STATUS VARCHAR(10),
  FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID) ON DELETE CASCADE
)""")
con.commit()

